package Game;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

public class GameBoard extends javax.swing.JFrame {

    public GameBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton17 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        isShowCards = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1340, 670));
        setPreferredSize(new java.awt.Dimension(1340, 670));
        setResizable(false);
        setSize(new java.awt.Dimension(1340, 670));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/area.png"))); // NOI18N
        jButton17.setBorder(null);
        jButton17.setOpaque(false);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17);
        jButton17.setBounds(650, 460, 119, 170);

        jButton24.setBackground(new java.awt.Color(255, 255, 255));
        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/closedcard.png"))); // NOI18N
        jButton24.setBorder(null);
        jButton24.setOpaque(false);
        getContentPane().add(jButton24);
        jButton24.setBounds(740, 240, 119, 170);

        jButton25.setBackground(new java.awt.Color(255, 255, 255));
        jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/closedcard.png"))); // NOI18N
        jButton25.setBorder(null);
        jButton25.setOpaque(false);
        getContentPane().add(jButton25);
        jButton25.setBounds(540, 240, 119, 170);

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/area.png"))); // NOI18N
        jButton15.setBorder(null);
        jButton15.setOpaque(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15);
        jButton15.setBounds(530, 460, 119, 170);

        jButton16.setBackground(new java.awt.Color(255, 255, 255));
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/area.png"))); // NOI18N
        jButton16.setToolTipText("99");
        jButton16.setBorder(null);
        jButton16.setOpaque(false);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16);
        jButton16.setBounds(770, 460, 119, 170);

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/area.png"))); // NOI18N
        jButton9.setToolTipText("99");
        jButton9.setBorder(null);
        jButton9.setOpaque(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(890, 460, 119, 170);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Oyuncu 1 : Kullanıcı ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1050, 550, 260, 50);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/area.png"))); // NOI18N
        jButton1.setToolTipText("");
        jButton1.setBorder(null);
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(410, 460, 119, 170);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Oyuncu 2 : Bilgisayar ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1050, 40, 290, 50);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Skor : 0");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(100, 500, 190, 80);

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/area.png"))); // NOI18N
        jButton20.setBorder(null);
        jButton20.setOpaque(false);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton20);
        jButton20.setBounds(540, 0, 119, 170);

        jButton23.setBackground(new java.awt.Color(255, 255, 255));
        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/area.png"))); // NOI18N
        jButton23.setToolTipText("99");
        jButton23.setBorder(null);
        jButton23.setOpaque(false);
        getContentPane().add(jButton23);
        jButton23.setBounds(900, 0, 119, 170);

        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/area.png"))); // NOI18N
        jButton22.setBorder(null);
        jButton22.setOpaque(false);
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton22);
        jButton22.setBounds(660, 0, 119, 170);

        jButton21.setBackground(new java.awt.Color(255, 255, 255));
        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/area.png"))); // NOI18N
        jButton21.setToolTipText("99");
        jButton21.setBorder(null);
        jButton21.setOpaque(false);
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton21);
        jButton21.setBounds(780, 0, 119, 170);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Skor : 0");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(100, 50, 180, 80);

        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextArea1.setFocusable(false);
        jTextArea1.setOpaque(false);
        getContentPane().add(jTextArea1);
        jTextArea1.setBounds(875, 260, 440, 150);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ORTADAKİ KARTLAR");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(160, 220, 148, 17);

        jButton18.setBackground(new java.awt.Color(255, 255, 255));
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/area.png"))); // NOI18N
        jButton18.setBorder(null);
        jButton18.setOpaque(false);
        getContentPane().add(jButton18);
        jButton18.setBounds(540, 240, 119, 170);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/area.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setOpaque(false);
        getContentPane().add(jButton2);
        jButton2.setBounds(740, 240, 119, 170);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/arena.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(680, 240, 60, 190);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/area.png"))); // NOI18N
        jButton12.setBorder(null);
        jButton12.setOpaque(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(370, 240, 119, 170);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/area.png"))); // NOI18N
        jButton11.setBorder(null);
        jButton11.setOpaque(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(250, 240, 119, 170);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/area.png"))); // NOI18N
        jButton8.setBorder(null);
        jButton8.setOpaque(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(130, 240, 119, 170);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/area.png"))); // NOI18N
        jButton10.setBorder(null);
        jButton10.setOpaque(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(10, 240, 119, 170);

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/area.png"))); // NOI18N
        jButton19.setBorder(null);
        jButton19.setOpaque(false);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton19);
        jButton19.setBounds(420, 0, 120, 170);

        isShowCards.setBackground(new java.awt.Color(255, 255, 255));
        isShowCards.setForeground(new java.awt.Color(255, 255, 255));
        isShowCards.setText("Kartları Göster");
        isShowCards.setBorder(null);
        isShowCards.setOpaque(false);
        isShowCards.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isShowCardsActionPerformed(evt);
            }
        });
        getContentPane().add(isShowCards);
        isShowCards.setBounds(10, 10, 140, 15);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bdtext.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(870, 240, 450, 170);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ana Menüye Dön");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(1210, 10, 120, 20);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bg1.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 1330, 630);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    int kart1, kart2, Roundp = 0, Roundc = 0, RoundF = 0;

    public void SetLeftArenaText(Game.Pokemon pokemon, int index) {
        //jButton18.setText("<html>" + pokemon.getPokemonAdi() + "<br /><br />" + "Güç : " + pokemon.hasarPuaniGoster() + "</html>");
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + pokemon.getPokemonAdi() + ".jpg")));

        jButton18.setToolTipText("" + index);
    }

    public void SetRightArenaText(Game.Pokemon pokemon, int index) {
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + pokemon.getPokemonAdi() + ".jpg")));
        jButton2.setToolTipText("" + index);

        switch (index) {
            case 0:
                jButton19.setEnabled(false);
                break;
            case 1:
                jButton20.setEnabled(false);
                break;
            case 2:
                jButton22.setEnabled(false);
                break;
            default:
                break;
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (Roundc == 0 && Roundp == 0) {
            jButton24.setVisible(true);
            jButton25.setVisible(true);
            jButton1.setEnabled(false);
            SetLeftArenaText(Gamer1.getKartList().get(0), 0);
            Gamer1.getKartList().get(0).setKartKullanildimi(true);

            Computer2Play(0);

            Roundp++;
        } else if (Roundc == 1 && Roundp == 1) {

            jButton24.setVisible(true);
            jButton25.setVisible(true);

            jButton1.setEnabled(false);
            SetLeftArenaText(Gamer1.getKartList().get(0), 0);
            Gamer1.getKartList().get(0).setKartKullanildimi(true);

            Computer2Play(0);

            Roundp++;
        } else if (Roundc == 2 && Roundp == 2) {

            jButton24.setVisible(true);
            jButton25.setVisible(true);
            jButton1.setEnabled(false);
            SetLeftArenaText(Gamer1.getKartList().get(0), 0);
            Gamer1.getKartList().get(0).setKartKullanildimi(true);

            Computer2Play(0);

            Roundc++;
        } else if (Roundc < 5 && Roundc > 2 && Roundp == 2) {
            jButton24.setVisible(true);
            jButton25.setVisible(true);
            jButton1.setEnabled(false);
            SetLeftArenaText(Gamer1.getKartList().get(0), 0);
            Gamer1.getKartList().get(0).setKartKullanildimi(true);
            Computer2Play(0);

            Roundc++;

        } else {
            JOptionPane.showMessageDialog(null, "Öncelikle Ortadan Kart Seçmelisiniz", "Uyarı !", 1);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed

        if (Roundc == 0 && Roundp == 0) {
            jButton24.setVisible(true);
            jButton25.setVisible(true);
            jButton15.setEnabled(false);
            SetLeftArenaText(Gamer1.getKartList().get(1), 1);
            Gamer1.getKartList().get(1).setKartKullanildimi(true);
            Computer2Play(1);

            Roundp++;
        } else if (Roundc == 1 && Roundp == 1) {
            jButton24.setVisible(true);
            jButton25.setVisible(true);
            jButton15.setEnabled(false);
            SetLeftArenaText(Gamer1.getKartList().get(1), 1);
            Gamer1.getKartList().get(1).setKartKullanildimi(true);
            Computer2Play(1);

            Roundp++;
        } else if (Roundc == 2 && Roundp == 2) {
            jButton24.setVisible(true);
            jButton25.setVisible(true);
            jButton15.setEnabled(false);
            SetLeftArenaText(Gamer1.getKartList().get(1), 1);
            Gamer1.getKartList().get(1).setKartKullanildimi(true);

            Computer2Play(1);

            Roundc++;
        } else if (Roundc < 5 && Roundc > 2 && Roundp == 2) {
            jButton24.setVisible(true);
            jButton25.setVisible(true);
            jButton15.setEnabled(false);
            SetLeftArenaText(Gamer1.getKartList().get(1), 1);
            Gamer1.getKartList().get(1).setKartKullanildimi(true);

            Computer2Play(1);

            Roundc++;

        } else {
            JOptionPane.showMessageDialog(null, "Öncelikle Ortadan Kart Seçmelisiniz", "Uyarı !", 1);
        }


    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed

        if (Roundp > 0) {

            if (Roundc == 0 && Roundp == 0) {
                jButton24.setVisible(true);
                jButton25.setVisible(true);
                jButton16.setEnabled(false);
                SetLeftArenaText(CommonCards.get(kart1), 1);
                CommonCards.get(kart1).setKartKullanildimi(true);

                Computer2PlayAfterCommon(kart1);

                Roundp++;
            } else if (Roundc == 1 && Roundp == 1) {
                jButton24.setVisible(true);
                jButton25.setVisible(true);
                jButton16.setEnabled(false);
                SetLeftArenaText(CommonCards.get(kart1), 1);
                CommonCards.get(kart1).setKartKullanildimi(true);

                Computer2PlayAfterCommon(kart1);

                Roundp++;
            } else if (Roundc == 2 && Roundp == 2) {
                jButton24.setVisible(true);
                jButton25.setVisible(true);
                jButton16.setEnabled(false);
                SetLeftArenaText(CommonCards.get(kart1), 1);
                CommonCards.get(kart1).setKartKullanildimi(true);

                Computer2PlayAfterCommon(kart1);

                Roundc++;
            } else if (Roundc < 5 && Roundc > 2 && Roundp == 2) {
                jButton24.setVisible(true);
                jButton25.setVisible(true);
                jButton16.setEnabled(false);
                SetLeftArenaText(CommonCards.get(kart1), 1);
                CommonCards.get(kart1).setKartKullanildimi(true);

                Computer2PlayAfterCommon(kart1);

                Roundc++;

            } else {
                JOptionPane.showMessageDialog(null, "Öncelikle Ortadan Kart Seçmelisiniz", "Uyarı !", 1);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Öncelikle Ortadan Kart Seçmelisiniz", "Uyarı !", 1);
        }
    }

    /* jButton18.setText("<html>" + CommonCards.get(index).getPokemonAdi() + "<br /><br />" + "Güç : " + CommonCards.get(index).hasarPuaniGoster() + "</html>");
        //   jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/"+CommonCards.get(index).getPokemonAdi()+".jpg"))); 
        //  jButton18.setToolTipText(""+index);
        //  CommonCards.get(index).setKartKullanildimi(true);
        //   Computer2PlayAfterCommon(index);
        //  DisableCommonCard(CommonCards.get(index).getPokemonAdi());
    }//GEN-LAST:event_jButton16ActionPerformed
   public boolean CheckGameIsFinish()
    {       
     for(Game.Pokemon poke: CommonCards)
        {
            if(poke.getKartKullanildimi() == false)
            {
                return false;
            }
        }       
        for(Game.Pokemon poke: Gamer1.getKartList())
        {
            if(poke.getKartKullanildimi() == false)
            {
                return false;
            }
        }
          return true;
    }
     */

 /*bu method 1. oyuncuya random kart seçtirecek common olanlar dahil seçim sonrası 2. oyuncuya kart seçtirilecek
      bu ikincinin seçim metodunu çağıracak ikinci karşılaştırma ve puan atama yapacak
      ikinci en son tekrar bu metodu çağıracak eğer hala kullanılmamış kart var ise  */
    public void Computer1Play() {
        if (RoundF < 5) {
            boolean isGamer1Empty = true;
            for (Game.Pokemon poke : Gamer1.getKartList()) {
                if (poke.getKartKullanildimi() == false) {
                    isGamer1Empty = false;
                    break;
                }
            }

            Game.Pokemon pokemon = null;
            Game.Bilgisayar cpu = null;
            if (!isGamer1Empty) {
                pokemon = Gamer1.kartSec(null);
                cpu = (Game.Bilgisayar) Gamer1;
            }

            List<Game.Pokemon> activeCommonCards = new ArrayList();
            for (Game.Pokemon poke : CommonCards) {
                if (poke.getKartKullanildimi() == false) {
                    activeCommonCards.add(poke);
                }
            }
            if (!isGamer1Empty) {
                activeCommonCards.add(pokemon);
            }

            System.out.println(activeCommonCards.size());

            Random rand = new Random();
            int pokeIndex = rand.nextInt(activeCommonCards.size());
            Game.Pokemon pokemonSelected1 = activeCommonCards.get(pokeIndex);

            if (pokemonSelected1 != pokemon) {
                if (jButton16.getToolTipText() == "99" || jButton9.getToolTipText() == "99") {
                    if (jButton16.getToolTipText() == "99") {

                        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + pokemonSelected1.getPokemonAdi() + ".jpg")));
                        jButton16.setToolTipText("" + pokeIndex);
                        jButton16.setEnabled(false);
                    } else {

                        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + pokemonSelected1.getPokemonAdi() + ".jpg")));
                        jButton9.setToolTipText("" + pokeIndex);
                        jButton9.setEnabled(false);
                    }

                    jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + pokemonSelected1.getPokemonAdi() + ".jpg")));
                    jButton18.setToolTipText("" + pokeIndex);

                    int commonIndex = 0;
                    for (Game.Pokemon poke : CommonCards) {
                        if (poke.getPokemonID() == pokemonSelected1.getPokemonID()) {
                            break;
                        }
                        commonIndex++;
                    }
                    CommonCards.get(commonIndex).setKartKullanildimi(true);

                    Computer2PlayAfterCommon(commonIndex);
                    DisableCommonCard(CommonCards.get(commonIndex).getPokemonAdi());
                } else {
                    pokemonSelected1 = pokemon;
                    Gamer1.getKartList().get(cpu._lastCardIndex).setKartKullanildimi(true);

                    jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + Gamer1.getKartList().get(cpu._lastCardIndex).getPokemonAdi() + ".jpg")));
                    jButton18.setToolTipText("" + cpu._lastCardIndex);
                    Computer2Play(cpu._lastCardIndex);
                    ShowIconGamer1Card(Gamer1.getKartList().get(cpu._lastCardIndex).getPokemonAdi());
                }
            } else {
                SetRightArenaText(pokemon, cpu._lastCardIndex);
                Gamer1.getKartList().get(cpu._lastCardIndex).setKartKullanildimi(true);

                jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + Gamer1.getKartList().get(cpu._lastCardIndex).getPokemonAdi() + ".jpg")));
                jButton18.setToolTipText("" + cpu._lastCardIndex);
                Computer2Play(cpu._lastCardIndex);
                ShowIconGamer1Card(Gamer1.getKartList().get(cpu._lastCardIndex).getPokemonAdi());
            }
        } else {
            jButton1.setEnabled(false);
            jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + Gamer1.getKartList().get(0).getPokemonAdi() + ".jpg")));
            jButton15.setEnabled(false);
            jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + Gamer1.getKartList().get(1).getPokemonAdi() + ".jpg")));
            jButton17.setEnabled(false);
            jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + Gamer1.getKartList().get(2).getPokemonAdi() + ".jpg")));
            jButton10.setEnabled(false);
            jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + CommonCards.get(0).getPokemonAdi() + ".jpg")));
            jButton8.setEnabled(false);
            jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + CommonCards.get(1).getPokemonAdi() + ".jpg")));
            jButton11.setEnabled(false);
            jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + CommonCards.get(2).getPokemonAdi() + ".jpg")));
            jButton12.setEnabled(false);
            jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + CommonCards.get(3).getPokemonAdi() + ".jpg")));

            PrintResult();
        }
    }

    public void PrintResult() {
        if (Oyuncu1Skor > Oyuncu2Skor) {
            JOptionPane.showMessageDialog(null, "Oyun sona erdi. Kazanan Oyuncu 1 !", "Oyuncu 1 Kazandı !", 1);
            jTextArea1.append("Oyun sona erdi. Kazanan Oyuncu 1 !");
        } else if (Oyuncu1Skor < Oyuncu2Skor) {
            JOptionPane.showMessageDialog(null, "Oyun sona erdi. Kazanan Oyuncu 2 !", "Oyuncu 2 Kazandı !", 1);
            jTextArea1.append("Oyun sona erdi. Kazanan Oyuncu 2 !");
        } else {
            JOptionPane.showMessageDialog(null, "Oyun sona erdi. Oyun Berabere Bitti !", "Dostluk Kazandı !", 1);
            jTextArea1.append("Oyun sona erdi. Oyun Berabere Bitti !");
        }
        jButton24.setVisible(false);
        jButton25.setVisible(false);
        isShowCards.setEnabled(false);
    }

    public void Computer2Play(int gamer1Index) {
        Game.Pokemon pokemon = Gamer2.kartSec(null);
        Game.Bilgisayar cpu = (Game.Bilgisayar) Gamer2;

        List<Game.Pokemon> activeCommonCards = new ArrayList();
        for (Game.Pokemon poke : CommonCards) {
            if (poke.getKartKullanildimi() == false) {
                activeCommonCards.add(poke);
            }
        }
        activeCommonCards.add(pokemon);

        Random rand = new Random();
        int pokeIndex = rand.nextInt(activeCommonCards.size());
        Game.Pokemon pokemonSelected1 = activeCommonCards.get(pokeIndex);

        if (pokemonSelected1 != pokemon) {
            if (jButton21.getToolTipText() == "99" || jButton23.getToolTipText() == "99") {
                if (jButton21.getToolTipText() == "99") {

                    jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + pokemonSelected1.getPokemonAdi() + ".jpg")));
                    jButton21.setToolTipText("" + pokeIndex);
                    jButton21.setEnabled(false);
                } else {

                    jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + pokemonSelected1.getPokemonAdi() + ".jpg")));
                    jButton23.setToolTipText("" + pokeIndex);
                    jButton23.setEnabled(false);
                }

                int commonIndex = 0;
                for (Game.Pokemon poke : CommonCards) {
                    if (poke.getPokemonID() == pokemonSelected1.getPokemonID()) {
                        break;
                    }
                    commonIndex++;
                }
                CommonCards.get(commonIndex).setKartKullanildimi(true);

                DisableCommonCard(CommonCards.get(commonIndex).getPokemonAdi());
            } else {
                pokemon.setKartKullanildimi(true);

                pokemonSelected1 = pokemon;
                pokemonSelected1.setKartKullanildimi(true);

                SetRightArenaText(pokemon, cpu._lastCardIndex);
                ShowIconGamer2Card(pokemonSelected1.getPokemonAdi());
            }
        } else {
            pokemon.setKartKullanildimi(true);

            pokemonSelected1 = pokemon;
            pokemonSelected1.setKartKullanildimi(true);

            SetRightArenaText(pokemon, cpu._lastCardIndex);
            ShowIconGamer2Card(pokemonSelected1.getPokemonAdi());
        }

        jTextArea1.append("Oyuncu 1 : " + Gamer1.getKartList().get(gamer1Index).getPokemonAdi() + " : " + Gamer1.getKartList().get(gamer1Index).hasarPuaniGoster() + " vs ");
        jTextArea1.append("Oyuncu 2 : " + pokemonSelected1.getPokemonAdi() + " : " + pokemonSelected1.hasarPuaniGoster());
        RoundF++;

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + pokemonSelected1.getPokemonAdi() + ".jpg")));
        jButton2.setToolTipText("" + pokeIndex);

        if (Gamer1.getKartList().get(gamer1Index).hasarPuaniGoster() > pokemonSelected1.hasarPuaniGoster()) {
            jTextArea1.append(" Kazanan OYUNCU 1 \n");
            JOptionPane.showMessageDialog(null, Gamer1.getKartList().get(gamer1Index).getPokemonAdi() + " Kazandı", " ", 1);
            this.Oyuncu1Skor+=5;
        } else if (Gamer1.getKartList().get(gamer1Index).hasarPuaniGoster() < pokemonSelected1.hasarPuaniGoster()) {
            jTextArea1.append(" Kazanan OYUNCU 2 \n");
            JOptionPane.showMessageDialog(null, pokemonSelected1.getPokemonAdi() + " Kazandı", " ", 1);
            this.Oyuncu2Skor+=5;
        } else {
            jTextArea1.append(" BERABERE \n");
            JOptionPane.showMessageDialog(null, " Berabere", " ", 1);
            this.Oyuncu1Skor+=5;
            this.Oyuncu2Skor+=5;
        }
        jButton24.setVisible(false);
        jButton25.setVisible(false);
        jLabel9.setText("Skor : " + this.Oyuncu1Skor);
        jLabel10.setText("Skor : " + this.Oyuncu2Skor);
        if (Gamer1.getOyuncuId() == 2) {
            Computer1Play();
        } else {
            if (RoundF > 4) {
                PrintResult();
            }
        }
    }

    public void Computer2PlayAfterCommon(int gamer1Index) {
        Game.Pokemon pokemon = Gamer2.kartSec(null);
        Game.Bilgisayar cpu = (Game.Bilgisayar) Gamer2;

        List<Game.Pokemon> activeCommonCards = new ArrayList();
        for (Game.Pokemon poke : CommonCards) {
            if (poke.getKartKullanildimi() == false) {
                activeCommonCards.add(poke);
            }
        }
        activeCommonCards.add(pokemon);

        Random rand = new Random();
        int pokeIndex = rand.nextInt(activeCommonCards.size());
        Game.Pokemon pokemonSelected1 = activeCommonCards.get(pokeIndex);

        if (pokemonSelected1 != pokemon) {
            if (jButton21.getToolTipText() == "99" || jButton23.getToolTipText() == "99") {
                if (jButton21.getToolTipText() == "99") {

                    jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + pokemonSelected1.getPokemonAdi() + ".jpg")));

                    jButton21.setToolTipText("" + pokeIndex);
                    jButton21.setEnabled(false);
                } else {

                    jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + pokemonSelected1.getPokemonAdi() + ".jpg")));
                    jButton23.setToolTipText("" + pokeIndex);
                    jButton23.setEnabled(false);
                }

                int commonIndex = 0;
                for (Game.Pokemon poke : CommonCards) {
                    if (poke.getPokemonID() == pokemonSelected1.getPokemonID()) {
                        break;
                    }
                    commonIndex++;
                }
                CommonCards.get(commonIndex).setKartKullanildimi(true);

                DisableCommonCard(CommonCards.get(commonIndex).getPokemonAdi());
            } else {
                pokemon.setKartKullanildimi(true);

                pokemonSelected1 = pokemon;
                pokemonSelected1.setKartKullanildimi(true);

                SetRightArenaText(pokemon, cpu._lastCardIndex);
                ShowIconGamer2Card(pokemonSelected1.getPokemonAdi());
            }
        } else {
            pokemon.setKartKullanildimi(true);

            pokemonSelected1 = pokemon;
            pokemonSelected1.setKartKullanildimi(true);

            SetRightArenaText(pokemon, cpu._lastCardIndex);
            ShowIconGamer2Card(pokemonSelected1.getPokemonAdi());
        }

        jTextArea1.append("Oyuncu 1 : " + CommonCards.get(gamer1Index).getPokemonAdi() + " : " + CommonCards.get(gamer1Index).hasarPuaniGoster() + " vs ");
        jTextArea1.append("Oyuncu 2 : " + pokemonSelected1.getPokemonAdi() + " : " + pokemonSelected1.hasarPuaniGoster());

        RoundF++;

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + pokemonSelected1.getPokemonAdi() + ".jpg")));
        jButton2.setToolTipText("" + pokeIndex);

        if (CommonCards.get(gamer1Index).hasarPuaniGoster() > pokemonSelected1.hasarPuaniGoster()) {
            jTextArea1.append(" Kazanan OYUNCU 1 \n");
            this.Oyuncu1Skor+=5;
            JOptionPane.showMessageDialog(null, CommonCards.get(gamer1Index).getPokemonAdi() + " Kazandı", " ", 1);
        } else if (CommonCards.get(gamer1Index).hasarPuaniGoster() < pokemonSelected1.hasarPuaniGoster()) {
            jTextArea1.append(" Kazanan OYUNCU 2 \n");
            JOptionPane.showMessageDialog(null, pokemonSelected1.getPokemonAdi() + " Kazandı", " ", 1);
            this.Oyuncu2Skor+=5;
        } else {
            jTextArea1.append(" BERABERE \n");
            JOptionPane.showMessageDialog(null, " Berabere", " ", 1);
            this.Oyuncu1Skor+=5;
            this.Oyuncu2Skor+=5;
        }

        jButton24.setVisible(false);
        jButton25.setVisible(false);
        jLabel9.setText("Skor : " + this.Oyuncu1Skor);
        jLabel10.setText("Skor : " + this.Oyuncu2Skor);
        if (Gamer1.getOyuncuId() == 2) {
            Computer1Play();
        } else {
            if (RoundF > 4) {
                PrintResult();
            }
        }
    }

    public void DisableCommonCard(String CardName) {
        int commonIndex = 0;
        for (Pokemon poke : CommonCards) {
            if (CardName == poke.getPokemonAdi()) {
                break;
            }

            commonIndex++;
        }

        switch (commonIndex) {
            case 0:
                jButton10.setEnabled(false);
                jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + CommonCards.get(0).getPokemonAdi() + ".jpg")));
                break;
            case 1:
                jButton8.setEnabled(false);
                jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + CommonCards.get(1).getPokemonAdi() + ".jpg")));
                break;
            case 2:
                jButton11.setEnabled(false);
                jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + CommonCards.get(2).getPokemonAdi() + ".jpg")));
                break;
            case 3:
                jButton12.setEnabled(false);
                jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + CommonCards.get(3).getPokemonAdi() + ".jpg")));
                break;
            default:
                break;
        }
    }

    public void ShowIconGamer1Card(String CardName) {
        int commonIndex = 0;
        for (Pokemon poke : Gamer1.getKartList()) {
            if (CardName == poke.getPokemonAdi()) {
                break;
            }

            commonIndex++;
        }

        switch (commonIndex) {
            case 0:
                jButton1.setEnabled(false);
                jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + Gamer1.getKartList().get(0).getPokemonAdi() + ".jpg")));
                break;
            case 1:
                jButton15.setEnabled(false);
                jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + Gamer1.getKartList().get(1).getPokemonAdi() + ".jpg")));
                break;
            case 2:
                jButton17.setEnabled(false);
                jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + Gamer1.getKartList().get(2).getPokemonAdi() + ".jpg")));
                break;
            default:
                break;
        }
    }

    public void ShowIconGamer2Card(String CardName) {
        int commonIndex = 0;
        for (Pokemon poke : Gamer2.getKartList()) {
            if (CardName == poke.getPokemonAdi()) {
                break;
            }

            commonIndex++;
        }

        switch (commonIndex) {
            case 0:
                jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + Gamer2.getKartList().get(0).getPokemonAdi() + ".jpg")));
                break;
            case 1:
                jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + Gamer2.getKartList().get(1).getPokemonAdi() + ".jpg")));
                break;
            case 2:
                jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + Gamer2.getKartList().get(2).getPokemonAdi() + ".jpg")));
                break;
            default:
                break;
        }
    }

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed

        if (Roundc == 0 && Roundp == 0) {
            jButton24.setVisible(true);
            jButton25.setVisible(true);
            jButton17.setEnabled(false);
            SetLeftArenaText(Gamer1.getKartList().get(2), 2);
            Gamer1.getKartList().get(2).setKartKullanildimi(true);

            Computer2Play(2);

            Roundp++;
        } else if (Roundc == 1 && Roundp == 1) {
            jButton24.setVisible(true);
            jButton25.setVisible(true);
            jButton17.setEnabled(false);
            SetLeftArenaText(Gamer1.getKartList().get(2), 2);
            Gamer1.getKartList().get(2).setKartKullanildimi(true);

            Computer2Play(2);

            Roundp++;
        } else if (Roundc == 2 && Roundp == 2) {
            jButton24.setVisible(true);
            jButton25.setVisible(true);
            jButton17.setEnabled(false);
            SetLeftArenaText(Gamer1.getKartList().get(2), 2);
            Gamer1.getKartList().get(2).setKartKullanildimi(true);

            Computer2Play(2);

            Roundc++;
        } else if (Roundc < 5 && Roundc > 2 && Roundp == 2) {
            jButton24.setVisible(true);
            jButton25.setVisible(true);
            jButton17.setEnabled(false);
            SetLeftArenaText(Gamer1.getKartList().get(2), 2);
            Gamer1.getKartList().get(2).setKartKullanildimi(true);

            Computer2Play(2);

            Roundc++;

        } else {
            JOptionPane.showMessageDialog(null, "Öncelikle Ortadan Kart Seçmelisiniz", "Uyarı !", 1);
        }


    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed

    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed

    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed

    }//GEN-LAST:event_jButton22ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jTextArea1.setBackground(new Color(255, 255, 255, 100));

        CreateAllCards();

        jButton24.setVisible(false);
        jButton25.setVisible(false);
        if (Selection.getSelectedGameType() == 2) {
            // Bilgisayar vs Bilgisayar ise
            Gamer1 = new Game.Bilgisayar();
            Gamer2 = new Game.Bilgisayar();
            AssignCards();
            jLabel1.setText("Oyuncu 1 : Bilgisayar");
            jLabel2.setText("Oyuncu 2 : Bilgisayar");

            ShowHideScreen(true);
            ResetScreen();
            ShowHideCards(true);
            Computer1Play();
        } else {
            Gamer1 = new Game.Kullanici();
            Gamer2 = new Game.Bilgisayar();
            AssignCards();
            jLabel1.setText("Oyuncu 1 : Kullanıcı");
            jLabel2.setText("Oyuncu 2 : Bilgisayar");

            ShowHideScreen(true);
            ResetScreen();
        }
    }//GEN-LAST:event_formWindowOpened

    public void ShowHideScreen(boolean stat) {
        jLabel1.setVisible(stat);
        jLabel2.setVisible(stat);
        jLabel9.setVisible(stat);
        jLabel10.setVisible(stat);
        jTextArea1.setVisible(stat);
    }

    public void ResetScreen() {
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton8.setEnabled(true);
        jButton9.setEnabled(true);
        jButton10.setEnabled(true);
        jButton11.setEnabled(true);
        jButton12.setEnabled(true);

        jButton15.setEnabled(true);
        jButton16.setEnabled(true);
        jButton17.setEnabled(true);
        jButton18.setEnabled(true);
        jButton19.setEnabled(true);
        jButton20.setEnabled(true);
        jButton21.setEnabled(true);
        jButton22.setEnabled(true);
        jButton23.setEnabled(true);
        jButton16.setToolTipText("99");
        jButton9.setToolTipText("99");
        jButton21.setToolTipText("99");
        jButton23.setToolTipText("99");
    }

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        if (Roundp == 0) {
            JOptionPane.showMessageDialog(null, "Kart Çekebilmek İçin Öncelikle Destenizden Bir Kart Oynamanız Gerekli", "Uyarı !", 1);
        } else if (Roundp == 1 && Roundc == 0) {
            GetFromDeck(jButton10, 0);
            Roundc++;
        } else if (Roundp == 2 && Roundc == 1) {
            GetFromDeck(jButton10, 0);
            Roundc++;
        } else {
            JOptionPane.showMessageDialog(null, "Kart Çekebilmek İçin Öncelikle Destenizden Bir Kart Oynamanız Gerekli", "Uyarı !", 1);
        }


    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        if (Roundp == 0) {
            JOptionPane.showMessageDialog(null, "Kart Çekebilmek İçin Öncelikle Destenizden Bir Kart Oynamanız Gerekli", "Uyarı !", 1);
        } else if (Roundp == 1 && Roundc == 0) {
            GetFromDeck(jButton8, 1);
            Roundc++;
        } else if (Roundp == 2 && Roundc == 1) {
            GetFromDeck(jButton8, 1);
            Roundc++;
        } else {
            JOptionPane.showMessageDialog(null, "Kart Çekebilmek İçin Öncelikle Destenizden Bir Kart Oynamanız Gerekli", "Uyarı !", 1);
        }


    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

        if (Roundp == 0) {
            JOptionPane.showMessageDialog(null, "Kart Çekebilmek İçin Öncelikle Destenizden Bir Kart Oynamanız Gerekli", "Uyarı !", 1);
        } else if (Roundp == 1 && Roundc == 0) {
            GetFromDeck(jButton11, 2);
            Roundc++;
        } else if (Roundp == 2 && Roundc == 1) {
            GetFromDeck(jButton11, 2);
            Roundc++;
        } else {
            JOptionPane.showMessageDialog(null, "Kart Çekebilmek İçin Öncelikle Destenizden Bir Kart Oynamanız Gerekli", "Uyarı !", 1);
        }


    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed

        if (Roundp == 0) {
            JOptionPane.showMessageDialog(null, "Kart Çekebilmek İçin Öncelikle Destenizden Bir Kart Oynamanız Gerekli", "Uyarı !", 1);
        } else if (Roundp == 1 && Roundc == 0) {
            GetFromDeck(jButton12, 3);
            Roundc++;
        } else if (Roundp == 2 && Roundc == 1) {
            GetFromDeck(jButton12, 3);
            Roundc++;
        } else {
            JOptionPane.showMessageDialog(null, "Kart Çekebilmek İçin Öncelikle Destenizden Bir Kart Oynamanız Gerekli", "Uyarı !", 1);
        }

    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed

    }//GEN-LAST:event_jButton19ActionPerformed

    private void isShowCardsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isShowCardsActionPerformed
        ShowHideCards(isShowCards.isSelected());
    }//GEN-LAST:event_isShowCardsActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        if (Roundp > 1) {

            if (Roundc == 0 && Roundp == 0) {
                jButton24.setVisible(true);
                jButton25.setVisible(true);
                jButton9.setEnabled(false);
                SetLeftArenaText(CommonCards.get(kart2), 1);

                CommonCards.get(kart2).setKartKullanildimi(true);

                Computer2PlayAfterCommon(kart2);

                Roundp++;
            } else if (Roundc == 1 && Roundp == 1) {
                jButton24.setVisible(true);
                jButton25.setVisible(true);
                jButton9.setEnabled(false);
                SetLeftArenaText(CommonCards.get(kart2), 1);

                CommonCards.get(kart2).setKartKullanildimi(true);

                Computer2PlayAfterCommon(kart2);

                Roundp++;
            } else if (Roundc == 2 && Roundp == 2) {
                jButton24.setVisible(true);
                jButton25.setVisible(true);
                jButton9.setEnabled(false);
                SetLeftArenaText(CommonCards.get(kart2), 1);

                CommonCards.get(kart2).setKartKullanildimi(true);

                Computer2PlayAfterCommon(kart2);

                Roundc++;
            } else if (Roundc < 5 && Roundc > 2 && Roundp == 2) {
                jButton24.setVisible(true);
                jButton25.setVisible(true);
                jButton9.setEnabled(false);
                SetLeftArenaText(CommonCards.get(kart2), 1);

                CommonCards.get(kart2).setKartKullanildimi(true);

                Computer2PlayAfterCommon(kart2);

                Roundc++;
            } else {
                JOptionPane.showMessageDialog(null, "Öncelikle Ortadan Kart Seçmelisiniz", "Uyarı !", 1);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Öncelikle Ortadan Kart Seçmelisiniz", "Uyarı !", 1);
        }


    }//GEN-LAST:event_jButton9ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked

        this.setVisible(false);

        ResetScreen();
        MainMenu Mn = new MainMenu();
        Mn.setVisible(true);

    }//GEN-LAST:event_jLabel5MouseClicked

    public void GetFromDeck(javax.swing.JButton clickedButton, int index) {
        if (CommonCards.get(index).getKartKullanildimi() == false) {
            if (jButton16.getToolTipText() == "99" || jButton9.getToolTipText() == "99") {
                clickedButton.setEnabled(false);
                if (jButton16.getToolTipText() == "99") {
                    // jButton16.setText("<html>" + CommonCards.get(index).getPokemonAdi() + "<br /><br />" + "Güç : " + CommonCards.get(index).hasarPuaniGoster() + "</html>");
                    jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + CommonCards.get(index).getPokemonAdi() + ".jpg")));
                    jButton16.setToolTipText("" + index);
                    clickedButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + CommonCards.get(index).getPokemonAdi() + ".jpg")));
                    kart1 = index;

                } else {
                    //jButton9.setText("<html>" + CommonCards.get(index).getPokemonAdi() + "<br /><br />" + "Güç : " + CommonCards.get(index).hasarPuaniGoster() + "</html>");
                    jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + CommonCards.get(index).getPokemonAdi() + ".jpg")));
                    jButton9.setToolTipText("" + index);
                    clickedButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + CommonCards.get(index).getPokemonAdi() + ".jpg")));
                    kart2 = index;

                }
                CommonCards.get(index).setKartKullanildimi(true);
                DisableCommonCard(CommonCards.get(index).getPokemonAdi());

                /* jButton18.setText("<html>" + CommonCards.get(index).getPokemonAdi() + "<br /><br />" + "Güç : " + CommonCards.get(index).hasarPuaniGoster() + "</html>");
                   jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/"+CommonCards.get(index).getPokemonAdi()+".jpg"))); 
                   jButton18.setToolTipText(""+index);
                   CommonCards.get(index).setKartOynandimi(true);
                   Computer2PlayAfterCommon(index);
                 */
            } else {
                JOptionPane.showMessageDialog(null, "Ortadan En Fazla 2 Kart Alınabilir. Başka Kart Alamazsınız !", "Uyarı !", 1);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Bu kart daha önce kullanılmıştır alınamaz !", "Uyarı !", 1);
        }
    }

    public void SelectCommonCard(javax.swing.JButton clickedButton, int index) {
        if (CommonCards.get(index).getKartKullanildimi() == false) {
            if (jButton16.getToolTipText() == "99" || jButton9.getToolTipText() == "99") {
                clickedButton.setEnabled(false);
                if (jButton16.getToolTipText() == "99") {

                    jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + CommonCards.get(index).getPokemonAdi() + ".jpg")));

                    jButton16.setToolTipText("" + index);
                    jButton16.setEnabled(false);

                } else {

                    jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + CommonCards.get(index).getPokemonAdi() + ".jpg")));
                    jButton9.setToolTipText("" + index);
                    jButton9.setEnabled(false);
                }

                jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + CommonCards.get(index).getPokemonAdi() + ".jpg")));
                jButton18.setToolTipText("" + index);

                CommonCards.get(index).setKartKullanildimi(true);

                Computer2PlayAfterCommon(index);
                DisableCommonCard(CommonCards.get(index).getPokemonAdi());
            } else {
                JOptionPane.showMessageDialog(null, "Ortadan En Fazla 2 Kart Alınabilir. Başka Kart Alamazsınız !", "Uyarı !", 1);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Bu kart daha önce kullanılmıştır alınamaz !", "Uyarı !", 1);
        }
    }

    private static Game.Pokemon pokemonCards[] = new Game.Pokemon[10];
    private static List<Game.Pokemon> CommonCards = new ArrayList();
    private static Game.Oyuncu Gamer1;
    private static Game.Oyuncu Gamer2;
    private int Oyuncu1Skor = 0;
    private int Oyuncu2Skor = 0;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameBoard().setVisible(true);
            }
        });

    }

    private static void CreateAllCards() {
        pokemonCards[0] = (new Pokemons.Bulbasaur());
        pokemonCards[1] = (new Pokemons.Butterfree());
        pokemonCards[2] = (new Pokemons.Charmander());
        pokemonCards[3] = (new Pokemons.Jigglypuff());
        pokemonCards[4] = (new Pokemons.Meowth());
        pokemonCards[5] = (new Pokemons.Pikachu());
        pokemonCards[6] = (new Pokemons.Psyduck());
        pokemonCards[7] = (new Pokemons.Snorlax());
        pokemonCards[8] = (new Pokemons.Squirtle());
        pokemonCards[9] = (new Pokemons.Zubat());
    }

    public void ShowHideCards(boolean isShow) {
        if (isShow) {
            jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + Gamer1.getKartList().get(0).getPokemonAdi() + ".jpg")));
            jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + Gamer1.getKartList().get(1).getPokemonAdi() + ".jpg")));
            jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + Gamer1.getKartList().get(2).getPokemonAdi() + ".jpg")));

            jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + Gamer2.getKartList().get(0).getPokemonAdi() + ".jpg")));
            jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + Gamer2.getKartList().get(1).getPokemonAdi() + ".jpg")));
            jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + Gamer2.getKartList().get(2).getPokemonAdi() + ".jpg")));

            jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + CommonCards.get(0).getPokemonAdi() + ".jpg")));
            jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + CommonCards.get(1).getPokemonAdi() + ".jpg")));
            jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + CommonCards.get(2).getPokemonAdi() + ".jpg")));
            jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + CommonCards.get(3).getPokemonAdi() + ".jpg")));
        } else {
            jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + Gamer1.getKartList().get(0).getPokemonAdi() + ".jpg")));
            jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + Gamer1.getKartList().get(1).getPokemonAdi() + ".jpg")));
            jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + Gamer1.getKartList().get(2).getPokemonAdi() + ".jpg")));

            jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/closedcard.png")));
            jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/closedcard.png")));
            jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/closedcard.png")));

            jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/closedcard.png")));
            jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/closedcard.png")));
            jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/closedcard.png")));
            jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/closedcard.png")));
        }
    }

    private void AssignCards() {
        CommonCards = new ArrayList();
        List<Integer> cardIndex = new ArrayList();
        cardIndex.add(0);
        cardIndex.add(1);
        cardIndex.add(2);
        cardIndex.add(3);
        cardIndex.add(4);
        cardIndex.add(5);
        cardIndex.add(6);
        cardIndex.add(7);
        cardIndex.add(8);
        cardIndex.add(9);

        Random rand = new Random();
        int random1, random2, random3, random4, random5, random6;

        random1 = rand.nextInt(10);
        do {
            random2 = rand.nextInt(10);
        } while (random1 == random2);
        do {
            random3 = rand.nextInt(10);
        } while (random3 == random1 || random3 == random2);
        do {
            random4 = rand.nextInt(10);
        } while (random4 == random1 || random4 == random2 || random4 == random3);
        do {
            random5 = rand.nextInt(10);
        } while (random5 == random1 || random5 == random2 || random5 == random3 || random5 == random4);
        do {
            random6 = rand.nextInt(10);
        } while (random6 == random1 || random6 == random2 || random6 == random3 || random6 == random4 || random6 == random5);

        Gamer1.listeyeKartEkle(pokemonCards[random1]);
        cardIndex.remove((Integer) random1);
        Gamer1.listeyeKartEkle(pokemonCards[random2]);
        cardIndex.remove((Integer) random2);
        Gamer1.listeyeKartEkle(pokemonCards[random3]);
        cardIndex.remove((Integer) random3);

        Gamer2.listeyeKartEkle(pokemonCards[random4]);
        cardIndex.remove((Integer) random4);
        Gamer2.listeyeKartEkle(pokemonCards[random5]);
        cardIndex.remove((Integer) random5);
        Gamer2.listeyeKartEkle(pokemonCards[random6]);
        cardIndex.remove((Integer) random6);

        for (int i : cardIndex) {
            CommonCards.add(pokemonCards[i]);
        }

        for (Game.Pokemon poke : Gamer1.getKartList()) {
            System.out.println("Gamer 1 pokemon : " + poke.getPokemonAdi());
        }

        for (Game.Pokemon poke : Gamer2.getKartList()) {
            System.out.println("Gamer 2 pokemon : " + poke.getPokemonAdi());
        }

        for (Game.Pokemon poke : CommonCards) {
            System.out.println("Ortadaki pokemon : " + poke.getPokemonAdi());
        }

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + Gamer1.getKartList().get(0).getPokemonAdi() + ".jpg")));
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + Gamer1.getKartList().get(1).getPokemonAdi() + ".jpg")));
        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cards/" + Gamer1.getKartList().get(2).getPokemonAdi() + ".jpg")));

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/closedcard.png")));
        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/closedcard.png")));
        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/closedcard.png")));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/closedcard.png")));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/closedcard.png")));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/closedcard.png")));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/closedcard.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox isShowCards;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
